# This workflow is desgined to update the official manifest file located at https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin
name: Official Manifest Updater
on:
  workflow_dispatch:
#   push:
#     branches:
#       - master

jobs:
  update_manifest:
    if: startsWith(github.repository, 'adoptium/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
          repository: docker-library/official-images

      - uses: actions/checkout@v2
        with:
          path: scripts

      - name: Run updater
        run: |
          cd scripts
          bash dockerhub_doc_config_update.sh ../library/eclipse-temurin
          cd ../
          rm -rf scripts

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
          commit-message: 'eclipse-temurin: dockerfile updates'
          author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"
          branch: eclipse-temurin
          title: 'eclipse-temurin: dockerfile updates'
          body: |
            This is an automatically created pull request from the official adoptium project.
            Please report any bugs at https://github.com/adoptium/containers.
